### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by Ygarr** [elbosso/webbrowser#5]
got this in console:
(OpenJDK 1.8)
java -jar target\webbrowser-1.2.0-SNAPSHOT-jar-with-dependencies.jar
```
30-Jul-2022 06:31:14 <ERROR> [AWT-EventQueue-0] ExceptionCatcher <clinit>.238 - Cannot invoke "java.net.URL.openStream()" because the return value of "java.lang.ClassLoader.getResource(String)" is null
java.lang.NullPointerException: Cannot invoke "java.net.URL.openStream()" because the return value of "java.lang.ClassLoader.getResource(String)" is null
        at de.netsysit.util.ResourceLoader.<clinit>(ResourceLoader.java:235)
        at de.netsysit.ui.components.DockingPanel.<clinit>(DockingPanel.java:12)
        at de.elbosso.webbrowser.WebBrowserTab.initAndShowGUI(WebBrowserTab.java:207)
        at de.elbosso.webbrowser.WebBrowserTab.<init>(WebBrowserTab.java:96)
        at de.elbosso.webbrowser.WebBrowser.initAndShowGUI(WebBrowser.java:63)
        at de.elbosso.webbrowser.WebBrowser.access$000(WebBrowser.java:47)
        at de.elbosso.webbrowser.WebBrowser$1.run(WebBrowser.java:111)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by elbosso** [comment]
ok - not pretty, but should not prevent from using it. still - not good, have to up dependencies to 1.9.0-SNAPSHOT to fix this...

**Comment by elbosso** [comment]
should be fixed now - can you please verify?

**Comment by Ygarr** [comment]
Now clear no stack traces while launching. Thanks
